services:
  spark:
    build:
      context: .
    container_name: spark
    environment:
      AWS_ACCESS_KEY_ID: console
      AWS_SECRET_ACCESS_KEY: console123
      ICEBERG_CATALOG: demo
      ICEBERG_DB: db
      ICEBERG_TABLE: persons
    networks:
      - datalake

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z 
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console UI
    environment:
      MINIO_ROOT_USER: console
      MINIO_ROOT_PASSWORD: console123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - datalake

volumes:
  minio_data:

networks:
  datalake:
    external: true