services:
  spark:
    image: apache/spark:3.5.7-python3
    container_name: spark    
    volumes:
      - ./jars:/opt/spark/work-dir
      - ./app:/app      
    command: [
      "/opt/spark/bin/spark-submit", 
      "--jars",
      "aws-java-sdk-bundle-1.12.262.jar,hadoop-aws-3.3.4.jar",
      "/app/test.py"
    ]

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z 
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console UI
    environment:
      MINIO_ROOT_USER: console
      MINIO_ROOT_PASSWORD: console123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
